run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - typecheck
    - gosec
    - gofmt
    - goimports
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - gosec
        - unused
