services:
  api:
    build: .
    container_name: register_system_api
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      # ảnh đã up lên sẽ được mount lại 
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  pgdata:
