basePath: /
definitions:
  model.AffiliationResponse:
    properties:
      description:
        type: string
      id:
        type: integer
      std_name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Backend API for the register system with JWT auth and role-based access.
  title: Register System API
  version: "1.0"
paths:
  /affiliations:
    get:
      description: Returns all valid affiliations for register form
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.AffiliationResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all affiliations
      tags:
      - Affiliation
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
